version: '3.5'

services:
    db:
        image: postgres:13.3
        ports:
          - '5432:5432'
        volumes:
          - ./scripts/db/:/docker-entrypoint-initdb.d/
        environment:
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
          - POSTGRES_DB=confinder