version: "3.5"

services:
  web:
    build: ./confinder.web
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    build:
      context: ./
      dockerfile: ./confinder.api/Dockerfile
    ports:
      - "7077:80"
    environment:
      - DB_CONNECTION_STRING=User ID=user;Password=password;Host=db;Port=5432;Database=confinder;Pooling=true
    depends_on:
      - db
  console:
    build:
      context: ./
      dockerfile: ./confinder.console/Dockerfile
    environment:
      - DB_CONNECTION_STRING=User ID=user;Password=password;Host=db;Port=5432;Database=confinder;Pooling=true
    depends_on:
      - db
  db:
    image: postgres:13.3
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/db/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=confinder
  doc:
    image: structurizr/lite
    ports:
      - "8081:8080"
    restart: always
    volumes:
      - ./structurizr.dsl:/usr/local/structurizr/workspace.dsl
