version: "3.5"

services:
  web:
    build: ./confinder.web
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    build:
      context: ./
      dockerfile: ./confinder.api/Dockerfile
    ports:
      - "7077:443"
    depends_on:
      - db
  db:
    image: postgres:13.3
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/db/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=confinder
